{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "toc_visible": true,
      "authorship_tag": "ABX9TyOU7v1gyAVsk1envU6a1jmy",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/triyulisirawan/test-recsam/blob/main/testing.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "fdb96054"
      },
      "source": [
        "## Computational Fluency Game\n",
        "\n",
        "This game is designed to help students practice basic arithmetic operations: addition, subtraction, and multiplication. It's built with beginner-friendly Python concepts, making it easy to understand and extend."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "0534a9dc"
      },
      "source": [
        "### 1. Game Logic\n",
        "\n",
        "-   **Operations**: The game will randomly generate questions involving addition, subtraction, or multiplication.\n",
        "-   **Number of Questions**: Each game session will consist of 5 questions.\n",
        "-   **Lives**: The player starts with 3 lives. Losing a life occurs when an incorrect answer is given.\n",
        "-   **Scoring**: A correct answer awards 10 points.\n",
        "-   **Feedback**: After each answer, the player receives immediate feedback, indicating whether their answer was correct or incorrect, and showing the correct answer if they were wrong.\n",
        "-   **Game End Conditions**: The game concludes either after all 5 questions have been asked, or if the player runs out of lives (lives reach 0), whichever comes first."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "a1790207"
      },
      "source": [
        "### 2. Game Flow\n",
        "\n",
        "1.  **Start**: Initialize `score` to 0, `lives` to 3, and `question_number` to 1.\n",
        "2.  **Loop**: Repeat the following steps for each question (up to 5 questions or until lives run out):\n",
        "    a.  **Generate Question**: Randomly select an operation (addition, subtraction, multiplication) and two numbers.\n",
        "    b.  **Display Question**: Present the question to the player.\n",
        "    c.  **Get Answer**: Prompt the player to enter their answer.\n",
        "    d.  **Check Answer**: Compare the player's input with the correct answer.\n",
        "    e.  **Provide Feedback & Update State**:\n",
        "        *   If correct: Display 'Correct!', add 10 points to `score`.\n",
        "        *   If incorrect: Display 'Incorrect.', show the correct answer, and subtract 1 life from `lives`.\n",
        "    f.  **Check Game Over**: If `lives` drops to 0, end the game immediately.\n",
        "    g.  **Next Question**: Increment `question_number`.\n",
        "3.  **End**: Display the final score and a game over message (indicating if they ran out of lives or completed all questions)."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "a2d8174c"
      },
      "source": [
        "### 3. Game State\n",
        "\n",
        "To keep track of the game's progress, we will use the following variables:\n",
        "\n",
        "-   `score`: An integer representing the player's current score, initialized to 0.\n",
        "-   `lives`: An integer representing the number of lives the player has remaining, initialized to 3.\n",
        "-   `question_count`: An integer to track how many questions have been asked, initialized to 0.\n",
        "-   `MAX_QUESTIONS`: A constant integer defining the total number of questions in a game, set to 5.\n",
        "-   `MAX_NUMBER`: A constant integer to set the upper limit for random numbers in questions, e.g., 10 or 12."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "74cbb017",
        "outputId": "dc46aa04-fa24-428b-df1a-145842ee590d"
      },
      "source": [
        "import random\n",
        "\n",
        "def play_math_game():\n",
        "    score = 0\n",
        "    lives = 3\n",
        "    total_questions_attempted = 0\n",
        "    MAX_QUESTIONS_PER_LEVEL = 5\n",
        "\n",
        "    # Level settings: defines the maximum number used for questions in each level\n",
        "    level_settings = {\n",
        "        'basic': {'max_num': 12},\n",
        "        'intermediate': {'max_num': 25},\n",
        "        'advanced': {'max_num': 50}\n",
        "    }\n",
        "\n",
        "    # --- Bilingual UI Messages ---\n",
        "    messages = {\n",
        "        'en': {\n",
        "            'welcome': \"--- 🚀 Welcome to the Computational Fluency Game! 🚀 ---\",\n",
        "            'info': \"You have {lives} ❤️ lives. Advance levels by answering 3 questions correctly in a row or completing 5 questions in a level. \\n\",\n",
        "            'choose_level': \"Choose your starting difficulty level (basic, intermediate, advanced): \",\n",
        "            'invalid_level': \"Invalid choice. Please type 'basic', 'intermediate', or 'advanced'.\",\n",
        "            'level_chosen': \"Great! You've chosen the {level} level to start. Let's begin! 👇\\n\",\n",
        "            'starting_level': \"--- Starting {level_name} level! Numbers up to {max_num}. ---\",\n",
        "            'question': \"Question {q_num}: What is {num1} {operation} {num2}? 🤔 \",\n",
        "            'invalid_input': \"Invalid input! 🚫 Please enter a number.\",\n",
        "            'correct': \"Correct! 🎉 Your score: {score} 🌟, Lives: {lives} ❤️\\n\",\n",
        "            'incorrect': \"Incorrect. ❌ The correct answer was {correct_answer}. Your score: {score} 🌟, Lives: {lives} ❤️\\n\",\n",
        "            'no_lives': \"Oh no! 😭 You've run out of lives.\",\n",
        "            'level_up_streak': \"🎉 Level Up! You mastered {level_name} by answering 3 correctly in a row! 🚀\",\n",
        "            'level_up_completed': \"✅ Level Up! You completed all questions in {level_name}! 🚀\",\n",
        "            'next_level': \"Next up: {level_name} level! Prepare yourself! 👇\",\n",
        "            'all_levels_completed': \"🏆 Congratulations! You've completed all levels! You are a Math Master! ✨\",\n",
        "            'game_over': \"--- Game Over! 🏁 ---\",\n",
        "            'questions_answered': \"Total Questions Attempted: {q_count}. 📝\",\n",
        "            'final_score': \"Final Score: {score} 🏆\",\n",
        "            'completed_all': \"Congratulations, you finished the game! ✨\",\n",
        "            'try_again': \"Better luck next time! 👍\"\n",
        "        },\n",
        "        'id': {\n",
        "            'welcome': \"--- 🚀 Selamat Datang di Permainan Kelancaran Berhitung! 🚀 ---\",\n",
        "            'info': \"Anda memiliki {lives} ❤️ nyawa. Naikkan level dengan menjawab 3 pertanyaan dengan benar berturut-turut atau menyelesaikan 5 pertanyaan dalam satu level. \\n\",\n",
        "            'choose_level': \"Pilih tingkat kesulitan awal Anda (basic, intermediate, advanced): \",\n",
        "            'invalid_level': \"Pilihan tidak valid. Mohon ketik 'basic', 'intermediate', atau 'advanced'.\",\n",
        "            'level_chosen': \"Bagus! Anda memilih level {level} untuk memulai. Ayo mulai! 👇\\n\",\n",
        "            'starting_level': \"--- Memulai level {level_name}! Angka hingga {max_num}. ---\",\n",
        "            'question': \"Pertanyaan {q_num}: Berapakah {num1} {operation} {num2}? 🤔 \",\n",
        "            'invalid_input': \"Masukan tidak valid! 🚫 Mohon masukkan angka.\",\n",
        "            'correct': \"Benar! 🎉 Skor Anda: {score} 🌟, Nyawa: {lives} ❤️\\n\",\n",
        "            'incorrect': \"Salah. ❌ Jawaban yang benar adalah {correct_answer}. Skor Anda: {score} 🌟, Nyawa: {lives} ❤️\\n\",\n",
        "            'no_lives': \"Oh tidak! 😭 Nyawa Anda habis.\",\n",
        "            'level_up_streak': \"🎉 Naik Level! Anda menguasai level {level_name} dengan menjawab 3 benar berturut-turut! 🚀\",\n",
        "            'level_up_completed': \"✅ Naik Level! Anda menyelesaikan semua pertanyaan di level {level_name}! 🚀\",\n",
        "            'next_level': \"Selanjutnya: level {level_name}! Bersiaplah! 👇\",\n",
        "            'all_levels_completed': \"🏆 Selamat! Anda telah menyelesaikan semua level! Anda adalah Master Matematika! ✨\",\n",
        "            'game_over': \"--- Permainan Selesai! 🏁 ---\",\n",
        "            'questions_answered': \"Total Pertanyaan yang Dicoba: {q_count}. 📝\",\n",
        "            'final_score': \"Skor Akhir: {score} 🏆\",\n",
        "            'completed_all': \"Selamat, Anda menyelesaikan permainan! ✨\",\n",
        "            'try_again': \"Semoga berhasil di lain waktu! 👍\"\n",
        "        }\n",
        "    }\n",
        "\n",
        "    # Language Selection\n",
        "    lang = input(\"Choose your language (en/id): \").lower()\n",
        "    while lang not in ['en', 'id']:\n",
        "        lang = input(\"Invalid choice. Please type 'en' for English or 'id' for Indonesian: \").lower()\n",
        "\n",
        "    print(messages[lang]['welcome'])\n",
        "    print(messages[lang]['info'].format(lives=lives))\n",
        "\n",
        "    # Level setup\n",
        "    level_names = list(level_settings.keys())\n",
        "    current_level_index = 0\n",
        "\n",
        "    # Initial Level Selection\n",
        "    chosen_start_level = input(messages[lang]['choose_level']).lower()\n",
        "    while chosen_start_level not in level_settings:\n",
        "        chosen_start_level = input(messages[lang]['invalid_level']).lower()\n",
        "    current_level_index = level_names.index(chosen_start_level)\n",
        "    current_level_name = chosen_start_level\n",
        "\n",
        "    print(messages[lang]['level_chosen'].format(level=current_level_name))\n",
        "\n",
        "    operations = ['+', '-', '*', '/']\n",
        "\n",
        "    # Outer loop for levels\n",
        "    while lives > 0 and current_level_index < len(level_names):\n",
        "        current_level_name = level_names[current_level_index] # Ensure current_level_name is always updated\n",
        "        MAX_NUMBER = level_settings[current_level_name]['max_num']\n",
        "        question_count_in_level = 0\n",
        "        consecutive_correct_answers = 0\n",
        "\n",
        "        print(messages[lang]['starting_level'].format(level_name=current_level_name.capitalize(), max_num=MAX_NUMBER))\n",
        "\n",
        "        # Inner loop for questions within a level\n",
        "        while question_count_in_level < MAX_QUESTIONS_PER_LEVEL and lives > 0 and consecutive_correct_answers < 3:\n",
        "            question_count_in_level += 1\n",
        "            total_questions_attempted += 1\n",
        "\n",
        "            operation = random.choice(operations)\n",
        "\n",
        "            if operation == '/':\n",
        "                # Ensure divisor is not zero and result is whole number\n",
        "                num2 = random.randint(1, MAX_NUMBER) # Divisor\n",
        "                # Choose a correct_answer (quotient) such that num2 * correct_answer <= MAX_NUMBER\n",
        "                max_possible_quotient = MAX_NUMBER // num2 if num2 != 0 else 1\n",
        "                if max_possible_quotient == 0:\n",
        "                    max_possible_quotient = 1 # Ensures quotient is at least 1\n",
        "                correct_answer = random.randint(1, max_possible_quotient)\n",
        "                num1 = num2 * correct_answer\n",
        "            else:\n",
        "                num1 = random.randint(1, MAX_NUMBER)\n",
        "                num2 = random.randint(1, MAX_NUMBER)\n",
        "                # Ensure subtraction doesn't result in negative for beginner-friendly\n",
        "                if operation == '-' and num1 < num2:\n",
        "                    num1, num2 = num2, num1 # Swap to ensure num1 >= num2\n",
        "\n",
        "                # Calculate the correct answer for +, -, *\n",
        "                if operation == '+':\n",
        "                    correct_answer = num1 + num2\n",
        "                elif operation == '-':\n",
        "                    correct_answer = num1 - num2\n",
        "                else: # operation == '*'\n",
        "                    correct_answer = num1 * num2\n",
        "\n",
        "            question_str = messages[lang]['question'].format(q_num=question_count_in_level, num1=num1, operation=operation, num2=num2)\n",
        "\n",
        "            try:\n",
        "                player_answer = int(input(question_str))\n",
        "            except ValueError:\n",
        "                print(messages[lang]['invalid_input'])\n",
        "                player_answer = None # Set to None to mark as incorrect\n",
        "\n",
        "            if player_answer == correct_answer:\n",
        "                score += 10\n",
        "                consecutive_correct_answers += 1\n",
        "                print(messages[lang]['correct'].format(score=score, lives=lives))\n",
        "            else:\n",
        "                lives -= 1\n",
        "                consecutive_correct_answers = 0 # Reset streak on incorrect answer\n",
        "                if player_answer is not None: # Only show incorrect if they actually entered something\n",
        "                    print(messages[lang]['incorrect'].format(correct_answer=correct_answer, score=score, lives=lives))\n",
        "                if lives == 0:\n",
        "                    print(messages[lang]['no_lives'])\n",
        "                    break # Break from inner loop if lives run out\n",
        "\n",
        "        # Check for level advancement conditions after inner loop finishes (either by questions, streak, or lives)\n",
        "        if lives > 0: # Only check for advancement if game is not over due to lives\n",
        "            if consecutive_correct_answers >= 3: # Advanced by streak\n",
        "                print(messages[lang]['level_up_streak'].format(level_name=current_level_name.capitalize()))\n",
        "                current_level_index += 1\n",
        "                if current_level_index < len(level_names): # If there's a next level\n",
        "                    print(messages[lang]['next_level'].format(level_name=level_names[current_level_index].capitalize()))\n",
        "                # Else, all levels completed, outer loop condition will handle termination\n",
        "            elif question_count_in_level == MAX_QUESTIONS_PER_LEVEL: # Advanced by completing all questions in level\n",
        "                print(messages[lang]['level_up_completed'].format(level_name=current_level_name.capitalize()))\n",
        "                current_level_index += 1\n",
        "                if current_level_index < len(level_names): # If there's a next level\n",
        "                    print(messages[lang]['next_level'].format(level_name=level_names[current_level_index].capitalize()))\n",
        "                # Else, all levels completed\n",
        "        else:\n",
        "            break # Break outer loop if lives ran out during a level\n",
        "\n",
        "    print(messages[lang]['game_over'])\n",
        "    print(messages[lang]['questions_answered'].format(q_count=total_questions_attempted))\n",
        "    print(messages[lang]['final_score'].format(score=score))\n",
        "\n",
        "    if lives > 0 and current_level_index >= len(level_names): # Player won by completing all levels\n",
        "        print(messages[lang]['all_levels_completed'])\n",
        "    else: # Player lost or did not complete all levels\n",
        "        print(messages[lang]['try_again'])\n",
        "\n",
        "# Run the game\n",
        "play_math_game()"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Choose your language (en/id): id\n",
            "--- 🚀 Selamat Datang di Permainan Kelancaran Berhitung! 🚀 ---\n",
            "Anda memiliki 3 ❤️ nyawa. Naikkan level dengan menjawab 3 pertanyaan dengan benar berturut-turut atau menyelesaikan 5 pertanyaan dalam satu level. \n",
            "\n",
            "Pilih tingkat kesulitan awal Anda (basic, intermediate, advanced): basic\n",
            "Bagus! Anda memilih level basic untuk memulai. Ayo mulai! 👇\n",
            "\n",
            "--- Memulai level Basic! Angka hingga 12. ---\n",
            "Pertanyaan 1: Berapakah 6 + 7? 🤔 13\n",
            "Benar! 🎉 Skor Anda: 10 🌟, Nyawa: 3 ❤️\n",
            "\n",
            "Pertanyaan 2: Berapakah 9 * 12? 🤔 108\n",
            "Benar! 🎉 Skor Anda: 20 🌟, Nyawa: 3 ❤️\n",
            "\n",
            "Pertanyaan 3: Berapakah 11 + 2? 🤔 21\n",
            "Salah. ❌ Jawaban yang benar adalah 13. Skor Anda: 20 🌟, Nyawa: 2 ❤️\n",
            "\n",
            "Pertanyaan 4: Berapakah 5 * 12? 🤔 60\n",
            "Benar! 🎉 Skor Anda: 30 🌟, Nyawa: 2 ❤️\n",
            "\n",
            "Pertanyaan 5: Berapakah 6 * 3? 🤔 18\n",
            "Benar! 🎉 Skor Anda: 40 🌟, Nyawa: 2 ❤️\n",
            "\n",
            "✅ Naik Level! Anda menyelesaikan semua pertanyaan di level Basic! 🚀\n",
            "Selanjutnya: level Intermediate! Bersiaplah! 👇\n",
            "--- Memulai level Intermediate! Angka hingga 25. ---\n",
            "Pertanyaan 1: Berapakah 10 / 2? 🤔 5\n",
            "Benar! 🎉 Skor Anda: 50 🌟, Nyawa: 2 ❤️\n",
            "\n",
            "Pertanyaan 2: Berapakah 17 * 16? 🤔 12\n",
            "Salah. ❌ Jawaban yang benar adalah 272. Skor Anda: 50 🌟, Nyawa: 1 ❤️\n",
            "\n",
            "Pertanyaan 3: Berapakah 19 + 11? 🤔 234\n",
            "Salah. ❌ Jawaban yang benar adalah 30. Skor Anda: 50 🌟, Nyawa: 0 ❤️\n",
            "\n",
            "Oh tidak! 😭 Nyawa Anda habis.\n",
            "--- Permainan Selesai! 🏁 ---\n",
            "Total Pertanyaan yang Dicoba: 8. 📝\n",
            "Skor Akhir: 50 🏆\n",
            "Semoga berhasil di lain waktu! 👍\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "30bae335"
      },
      "source": [
        "### 5. Important Parts of the Code Explanation\n",
        "\n",
        "Let's break down the key elements of the Python code:\n",
        "\n",
        "1.  **`import random`**: This line imports the `random` module, which is essential for generating random numbers for `num1` and `num2`, and for choosing a random arithmetic `operation`.\n",
        "\n",
        "2.  **`play_math_game()` function**: The entire game logic is encapsulated within this function. This makes the code organized and reusable.\n",
        "\n",
        "3.  **Initialization**:\n",
        "    *   `score = 0`, `lives = 3`, `total_questions_attempted = 0`: These variables are set at the start of each game to track the player's progress. `total_questions_attempted` now tracks questions across all levels.\n",
        "    *   `MAX_QUESTIONS_PER_LEVEL = 5`: Defines the total number of questions within each level.\n",
        "    *   `level_settings` dictionary: This dictionary defines the `max_num` (maximum number for question generation) for each difficulty level ('basic', 'intermediate', 'advanced').\n",
        "    *   `current_level_index`, `current_level_name`, `consecutive_correct_answers`: New variables to manage the player's current level and track consecutive correct answers for automatic level progression.\n",
        "\n",
        "4.  **`messages` dictionary**: This dictionary holds all the user-facing text for the game in both English (`'en'`) and Indonesian (`'id'`), including new messages for level progression.\n",
        "\n",
        "5.  **Language Selection**: The game prompts the user to choose their preferred language (en/id) at the beginning, making the game more accessible.\n",
        "\n",
        "6.  **Initial Level Selection**: The player is prompted to choose their starting difficulty level. The game will then track `current_level_name` and `current_level_index` for progression.\n",
        "\n",
        "7.  **`operations = ['+', '-', '*', '/']`**: A list of strings representing the possible arithmetic operations, including division (`'/'`). `random.choice(operations)` is used to pick one for each question.\n",
        "\n",
        "8.  **Outer Loop for Levels**: The game now has an outer `while` loop that iterates through the `level_names`. This loop continues as long as the player has `lives` and there are more levels to play.\n",
        "\n",
        "9.  **Inner Loop for Questions within a Level**: Inside the level loop, another `while` loop runs for questions. It continues as long as `question_count_in_level < MAX_QUESTIONS_PER_LEVEL`, `lives > 0`, and `consecutive_correct_answers < 3` (for early level advancement).\n",
        "\n",
        "10. **Question Generation (with Refined Division Logic)**:\n",
        "    *   `num1 = random.randint(1, MAX_NUMBER)` and `num2 = random.randint(1, MAX_NUMBER)`: Generate two random integers for addition, subtraction, and multiplication, respecting the current `MAX_NUMBER` for the level.\n",
        "    *   `if operation == '-' and num1 < num2: num1, num2 = num2, num1`: This important check ensures that for subtraction, the first number is always greater than or equal to the second, preventing negative answers for a beginner-friendly experience.\n",
        "    *   **Refined Division Logic**: For division (`operation == '/'`), `num2` (divisor) and `correct_answer` (quotient) are chosen first. Then `num1` (dividend) is calculated as `num2 * correct_answer`. Crucially, `max_possible_quotient` is calculated to ensure that `num1` does not exceed the current `MAX_NUMBER` and that the division always results in a whole number.\n",
        "\n",
        "11. **`input(question_str)`**: This function pauses the program and waits for the player to type their answer and press Enter. The entered text is then captured.\n",
        "\n",
        "12. **`try-except ValueError` block**: This handles potential errors if the player types something that is not a valid number (e.g., text) when prompted for an answer. It prevents the program from crashing and provides user-friendly feedback.\n",
        "\n",
        "13. **`if player_answer == correct_answer:`**: This `if-else` statement checks if the player's answer matches the calculated `correct_answer`.\n",
        "    *   If correct: The `score` is increased, and `consecutive_correct_answers` is incremented.\n",
        "    *   If incorrect: A `life` is subtracted, `consecutive_correct_answers` is reset to 0, and the correct answer is revealed. It also checks `if lives == 0:` to end the game early if needed.\n",
        "\n",
        "14. **Level Advancement Conditions**: After each inner question loop finishes, the code checks if the player should advance to the next level:\n",
        "    *   If `consecutive_correct_answers >= 3`, the player advances by streak.\n",
        "    *   If `question_count_in_level == MAX_QUESTIONS_PER_LEVEL`, the player advances by completing all questions in the current level.\n",
        "    *   The `current_level_index` is updated, and appropriate messages are displayed.\n",
        "\n",
        "15. **Game Over Messages**: After all levels are played or lives run out, the code prints the `Final Score`, the `total_questions_attempted`, and a concluding message based on whether the player successfully completed all levels or ran out of lives."
      ]
    }
  ]
}